### ISSUE TITLE
Support new template config format

### ISSUE THREAD

**Issue by lovesegfault** [SenchoPens/base16.nix#20]
It looks like tinted-theming is moving away from `config.yaml` files that look like [this](https://github.com/tinted-theming/tinted-foot/blob/05f27c44b1834ae8ca080778bff4efa3a88b4a25/templates/config.yaml):
```yaml
default:
  extension: .ini
  output: colors
```

And towards [this](https://github.com/tinted-theming/tinted-foot/blob/7ca954e993ee73a7cc9b86c59df4920cc8ff9d34/templates/config.yaml):
```yaml
base16:
  extension: .ini
  output: colors
  supported-systems: [base16]

base24:
  extension: .ini
  output: colors
  supported-systems: [base24]
```

Which is breaking base16.nix as it fails to find a `default` target in the config. We should probably move to looking for a `base16` default?
